const assert=require("assert");
const x=require("../canonical-troll.json");
assert.equal(x.asset,"TROLL");
assert.equal(x.role,"EVOLUTION_BURN_TOKEN");
assert.equal(x.expected_chain_id,4663);
assert.equal(x.contract_address,"0x2a13008CC2F5A853F6Fb21cbD90841806C64b247");
assert.equal(x.deployment_binding.contract,"TrollEvolutionEngineV19");
assert.equal(x.deployment_binding.constructor_parameter,"troll_");
assert.equal(x.deployment_binding.value,x.contract_address);
assert.equal(x.burn_sink.value,"0x000000000000000000000000000000000000dEaD");
assert.equal(x.verification_status,"ONCHAIN_VERIFIED_BLOCKSCOUT");
assert.equal(x.onchain_verification.chain_id,4663);
assert.equal(x.onchain_verification.token_name,"Troll in Hood");
assert.equal(x.onchain_verification.symbol,"TROLL");
assert.equal(x.onchain_verification.decimals,18);
assert.equal(x.onchain_verification.is_contract,true);
assert.equal(x.onchain_verification.is_verified_source,true);
assert.equal(x.onchain_verification.proxy_type,null);
console.log("CANONICAL TROLL PRODUCTION BINDING PASS");