const assert=require("assert");
const x=require("../launch-profile.json");
assert.equal(x.launch_profile,"CORE_ONLY_REGULATED_DISABLED");
assert.equal(x.chain_id,4663);
assert.equal(x.reviewed_contract_target.commit,"c3750b9458156e962393059f78c92e79802bf622");
assert.equal(x.canonical_troll.address,"0x2a13008CC2F5A853F6Fb21cbD90841806C64b247");
assert.equal(x.regulated_assets.production_enablement,false);
assert.equal(x.mainnet.broadcast,false);
assert.equal(x.multisig.target,"SAFE_2_OF_3");
assert.equal(x.risk_waivers.independent_human_audit.status,"WAIVED_BY_OWNER");
assert.ok(!x.blockers.includes("INDEPENDENT_HUMAN_AUDIT"));
assert.ok(!x.blockers.includes("FINAL_REVIEWED_COMMIT_FROZEN"));
assert.ok(!x.blockers.includes("EXPLICIT_MAINNET_AUTHORIZATION"));
assert.ok(!x.blockers.includes("REGULATED_SETTLEMENT_APPROVED"));
assert.equal(x.mainnet.authorization,"AUTHORIZED_CONDITIONAL_2026_09_28_EVENING");
assert.ok(x.blockers.includes("PRODUCTION_MULTISIG"));
assert.ok(x.blockers.includes("PRODUCTION_METADATA_CIDS"));
assert.ok(x.blockers.includes("DEDICATED_PRODUCTION_RPC"));
assert.ok(x.blockers.includes("FINAL_DEPLOYMENT_REHEARSAL"));
console.log("PRODUCTION LAUNCH PROFILE PASS");
