import assert from "node:assert/strict";
import{normalizeFinding,releaseImpact,reconcileFindings}from"../security/findings.mjs";
const a={id:"SEC-1",source:"CODEX",severity:"high",status:"OPEN",title:"Example"};
const b={id:"SEC-1",source:"HUMAN_AUDIT",severity:"HIGH",status:"CLOSED_VERIFIED",title:"Example",reviewer_verification:"reviewer"};
const c={id:"SEC-2",source:"SLITHER",severity:"LOW",status:"OPEN"};
assert.equal(normalizeFinding(a).severity,"HIGH");
const merged=reconcileFindings([a,c],[b]);assert.equal(merged.length,2);assert.equal(merged.find(x=>x.id==="SEC-1").status,"CLOSED_VERIFIED");
assert.equal(releaseImpact([a]).release_blocked,true);
assert.equal(releaseImpact([b,c]).release_blocked,false);
assert.throws(()=>normalizeFinding({...a,severity:"banana"}));
console.log("V34 SECURITY FINDINGS PIPELINE PASS");