const assert=require("assert");
const x=require("../safe-preflight.json");
assert.equal(x.chain_id,4663);
assert.equal(x.safe_version,"1.4.1");
assert.equal(x.production_safe.threshold,2);
assert.equal(x.production_safe.owner_count,3);
assert.equal(x.production_safe.owners_publication,"WITHHELD_PREDEPLOYMENT");
assert.equal(x.production_safe.status,"PRIVATE_REPLACEMENT_SIGNERS_CONFIRMED_SAFE_CREATION_PENDING");
assert.equal(x.production_safe.address,null);
assert.equal(x.signer_verification.unique_addresses_confirmed,true);
assert.equal(x.signer_verification.independent_recovery_phrases_confirmed,true);
assert.equal(x.signer_verification.public_addresses_in_repository,false);
assert.equal(x.canonical_contracts.proxy_factory,"0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67");
console.log("PRODUCTION SAFE PRIVATE SIGNER CONFIG PASS");